# Use Oracle Linux as the base image
FROM oraclelinux:8

# Install necessary packages for OCI CLI
RUN yum -y install unzip oraclelinux-developer-release-el8 && \
    yum -y install python36-oci-cli && \
    yum -y install openssh-clients && \
    yum -y install libaio oraclelinux-developer-release-el8 libnsl ncurses-compat-libs expect glibc-devel hostname numactl openssl python3 sudo && \
    yum clean all

# Set a default working directory
WORKDIR /tmp
